### ISSUE TITLE
Ingame Data is different

### ISSUE THREAD

**Issue by Maxxxel** [FrankTheBoxMonster/LoL-NGRID-converter#2]
Hey there, nice project you got there.
I tried to verify your data ingame, but it looks like they are different.
Check this example: https://i.gyazo.com/thumb/1200/b2c4b25559030e07f4a7e0c4c8fd9a2c-png.jpg
I measured ingame with a ward.

Yellow = Your Data
Green Stars = Ward Data

So it looks like Riot adds some post-processing to the data?
I tried to check for some more objects like wall and bushes and everytime one row to the top and right is missing compared to your data.

**Comment by FrankTheBoxMonster** [comment]
I'm not sure how you got the results you got but you absolutely did something wrong.  Both myself and other people have extensively tested the map for accuracy and have never found an issue before, nor have any of us been able to reproduce the exact inconsistency you are claiming around the blue side bot nexus turret.

![image](https://user-images.githubusercontent.com/11337782/119270135-39f35100-bbc9-11eb-8a1b-eb33a3d064e7.png)

This is what the navgrid looks like when properly accounting for an in-game fully zoomed camera perspective.  It completely matches what you are reporting with wards.

Whatever you did to translate my data into your image must have been incorrect.  It's possible that you thought you could just copypaste the navgrid onto an in-game screenshot and expect it to work.  The navgrid is a perfectly flat topdown image and the in-game camera is not, so that's not going to work.

**Comment by FrankTheBoxMonster** [comment]
I also have some very high resolution images overlaying the navgrid onto the map geometry elsewhere in the repo, they might be helpful to whatever you are trying to check for.  Sometimes it can take a bit for them to load to their full resolution.

https://github.com/FrankTheBoxMonster/LoL-NGRID-converter/tree/master/navgrid%20mapgeo%20overlays%20with%20structures

![image](https://user-images.githubusercontent.com/11337782/119270610-8b9cdb00-bbcb-11eb-8b83-e1d2206613e8.png)

**Comment by Maxxxel** [comment]
Is there some way to see the map from above like on the image?

**Comment by Maxxxel** [comment]
@FrankTheBoxMonster how can I test it like that

**Comment by FrankTheBoxMonster** [comment]
These images were created manually by converting the map geometry file and then overlaying the navgrid on top of that.  You can't view it like this in-game.

https://github.com/FrankTheBoxMonster/LoL-NGRID-converter/blob/master/navgrid%20mapgeo%20overlays%20with%20structures/SRX.png

This is the link to the full topdown overlay image.  It's been good enough for everyone else who has needed very precise visuals, so it should be good enough for you too.

**Comment by Maxxxel** [comment]
![](https://i.ibb.co/sPFz2Fc/Screenshot-20210524-002433-Chrome.jpg)

I think I found my problem. I was thinking in "Nodes" and not in "Cells":

Cell position (red)
Cell edges direction (yellow) 
Blue points are corner points marking the end of the cell.

3 cells have 4 points on one line in total 😚
