### ISSUE TITLE
Maps missing alcove

### ISSUE THREAD

**Issue by iaace-NA** [FrankTheBoxMonster/LoL-NGRID-converter#4]
Hello, are there any plans to update the example bitmaps to the new map which includes bot/top alcoves?

**Comment by Maxxxel** [comment]
Also noticed that the actual map file for howling abyss (extracted with Obsidian) miss stuff compared to the file uploaded here. 

Also I wondered if there are references to Qiyana using the Map?

**Comment by FrankTheBoxMonster** [comment]
@iaace-NA The alcoves are included under the [SummonersRiftSeason10](https://github.com/FrankTheBoxMonster/LoL-NGRID-converter/tree/master/test%20files/SummonersRiftSeason10) folder.

@Maxxxel Yeah the Howling Abyss navgrid has been updated at some point in the past four years.

Not sure what you want to know about Qiyana but she does use this same system for determining what is river/brush/wall.  Part of that Howling Abyss update seems to be when they made health packs count as river for her (also why Ezreal complains about stepping in water when you walk over them since he now thinks they are river too).

**Comment by Maxxxel** [comment]
I know that Qiyana uses more than just Wall/River/Brush flags, cause when you check Ingane with her Skill you see what kind of environment is at mouse position. And it looks like brushes, walls, structures and water have like a "zone" around them. But it looks handmade and not at a fixed distance, cause I found spots that show this. I can send you stuff, maybe you understand that xD

**Comment by FrankTheBoxMonster** [comment]
Qiyana has a ~350 units search radius for picking cells with the river/brush/wall flags.  Your cursor picks the nearest cell out of those three types within that radius (about 7 cells worth).  It's still based on those flags just with some extra help to make it easier to cast and to account for the navgrid not perfectly aligning with what appears to be river/brush/wall according to the map visuals.

**Comment by Maxxxel** [comment]
Nope, that's not correct for SR. I made them all by hand, it looks like RIOT also did that. Cause there is a river spot encapsulated by brush area at the river triangle botlane.

**Comment by Maxxxel** [comment]
I can send you a map I made later.

**Comment by Maxxxel** [comment]
@FrankTheBoxMonster Check this out:
![GenerateQiyanaMap](https://user-images.githubusercontent.com/10586721/184315567-ddd56392-89d4-4a44-851b-6acd35cddf7a.png)

Light Grey = Qiyana Extended Walls
Dark Blue = Qiyana Extended River
Dark GReen = Qiyana Extenden Bushes

Especially the River and Bush parts wont fit into the 350 Unit assumption, while it looks perfectly right for structures and most walls. I dont see a pattern for the rest.

**Comment by FrankTheBoxMonster** [comment]
Yes this is still consistent with what I said.  The river brushes don't have an extension because the area around them is still the river.  That makes the closest cell at those locations a river cell instead of a brush cell, since whatever cell your cursor is in will always be its closest cell.  Brush near walls is a similar thing, where some points will have the closest cell be a brush and sometimes the closest is a wall, and it always just picks the closest.

**Comment by Maxxxel** [comment]
How does this apply to that image ![](https://i.imgur.com/JpOkEdz.jpg)

**Comment by FrankTheBoxMonster** [comment]
This is because the way they determine closest cell is a sort of spiral out from the cursor.  This is also how they handle if you cast Flash into a wall to find the nearest opening or hitting a group of targets for a spell.

The game checks rings of cells until it finds a cell with brush, river, or wall.  If a ring has more than one, then it prioritizes them in that order and stops searching.  After the 8th ring, it gives up (the defined search radius is 366 units, which at 50 units per cell equals 7.32 cells, but gets rounded up to 8 cells, so the actual radius becomes 350-400 units depending on how close to a cell boundary your cursor is).

Your image was rather inaccurate except for the alcoves so I made my own.

![image](https://user-images.githubusercontent.com/11337782/184456524-f1efb1fc-6b51-409a-978f-d49096ce5410.png)
black = wall
green = brush
yellow = brush+wall (wall for pathing, brush for vision, counts as brush for Qiyana W but wall for placing a ward)
blue = not a brush cell but counts as one for Qiyana W

The cursor is in the single cell for ring 1.  There is no terrain cell in this ring, so it moves to ring 2, which also has no terrain cells.  This continues until ring 6, where it finds a brush+wall cell and a normal wall cell.  The brush+wall cell takes priority, so this cell counts as brush for Qiyana W.

![image](https://user-images.githubusercontent.com/11337782/184456555-8aa18a43-cbf9-44e0-8392-ebe94576d8d8.png)
Moving right one cell now causes the first ring with a terrain cell to become ring 5, which contains wall but no brush or brush+wall, so this cell counts as wall for Qiyana W.

![image](https://user-images.githubusercontent.com/11337782/184456625-9e9b1e51-7a03-469d-a9a7-b405da03950b.png)
Moving down one cell from there still has ring 5 as the first ring with a terrain cell, but it now contains the brush+wall cell, so this cell counts as brush for Qiyana W.

![image](https://user-images.githubusercontent.com/11337782/184456685-92b6dddd-51c6-47fe-8f19-44813901891c.png)
Moving to the bottom of this area, from this location ring 5 contains a single wall terrain cell, so this cell counts as wall for Qiyana W.

![image](https://user-images.githubusercontent.com/11337782/184456745-a478467a-469c-4629-a2a6-482a6bdc58c4.png)
Stepping to the right one cell from here causes ring 5 to now contain both wall cells and brush cells, so since brush always takes priority, this cell counts as brush for Qiyana W.

![image](https://user-images.githubusercontent.com/11337782/184456983-714c2552-4d12-47f4-9c99-eb2ee3b30b05.png)
And to show one more location, this is bot lane wall.  The starting cell here is out of range of the turret or wall, so this cell is not targetable by Qiyana W, since it fails to find a terrain cell by the final 8th ring.  Moving one cell right or down would put a wall cell into the 8th ring and allow the spell to be cast there.

I'll see if I can look into generating an accurate measurement of this effect for the entire map (these images I just painted over by hand after measuring them in-game).

**Comment by FrankTheBoxMonster** [comment]
Okay I realized that your image isn't completely inaccurate, but is instead upside down.  Since the alcoves are new, they are more symmetrical than the rest of the map, which is why they lined up.

What you posted, overlayed on the map render:
![image](https://user-images.githubusercontent.com/11337782/184458227-6842d2a3-10d5-4c47-adb0-776e84839dd3.png)


When I rotate your image 180 degrees:
![image](https://user-images.githubusercontent.com/11337782/184458215-91ee3560-0b47-4701-8d42-6c244ba882e7.png)


However your brush are still not accurate to what I measured even accounting for this.

**Comment by Maxxxel** [comment]
Well, I checked the spots with Qiyana in-game and my values were correct. Guess I wait for you to create one based on your theory and we compare it to mine. And thanks for the great explanation.

**Comment by Maxxxel** [comment]
![grafik](https://user-images.githubusercontent.com/10586721/187281418-c290a174-cae6-484d-8edd-a6abdd731778.png)

Left my Values from Hand
Right your described algorithm

I try to get an Account with Qiyana, but i doubt the Right values are correct, i remember the areas were rounded and not edgy.

**Comment by Maxxxel** [comment]
Ideas? 😁
